# Generated by Django 5.2.7 on 2025-10-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_employee_work_location_leaverecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_fraud',
            field=models.BooleanField(default=False),
        ),
    ]
