# Generated by Django 5.2.7 on 2025-10-22 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_employee_salary_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fraud_flags',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FraudDetector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scan_date', models.DateTimeField(auto_now=True)),
                ('suspicious_pattern_count', models.IntegerField(default=0)),
                ('total_suspicious_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.employee')),
            ],
            options={
                'db_table': 'FraudDetector',
            },
        ),
    ]
